name: CACHE
on:
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        if: success()
        # preferred
        with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
        cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
